import 'package:marathon/chats/chat1/conversion.dart';
import 'package:marathon/chats/chat1/message.dart';
import 'package:marathon/chats/chat1/user.dart';

class MessageProvider {
  static List<Conversion> getConversation() {
    User user1 = User(
      name: "Ahmed Ashraf",
      image: "assets/images/share/a.jpg",
    );
    User user2 = User(
      name: "Selena Alex",
      image: "assets/images/share/s.jpg",
    );
    User user3 = User(
      name: "Billie Eilish",
      image: "assets/images/share/eee.jpg",
    );
    User user4 = User(
      name: "Selena Gomez",
      image: "assets/images/share/e.jpg",
    );
    return [
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
    ];
  }

  static List<Conversion> getConversations() {
    User user1 = User(
      name: "Ahmed Ashraf",
      image: "assets/images/share/a.jpg",
    );
    User user2 = User(
      name: "Selena Alex",
      image: "assets/images/share/s.jpg",
    );
    User user3 = User(
      name: "Billie Eilish",
      image: "assets/images/share/eee.jpg",
    );
    User user4 = User(
      name: "Selena Gomez",
      image: "assets/images/share/e.jpg",
    );

    return [
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
      Conversion(
        users: [user1, user2, user3, user4],
        messages: [
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
          Message(
            sender: user1,
            receiver: user2,
            senders: user3,
            receivers: user4,
            dataTime: "22:36",
            data: "Today, 25",
            body: "Hi there How are you",
          ),
        ],
      ),
    ];
  }
}
