/// Generated by AssetsRefGenerator on 2020/10/13
class Res {
  static const String NotoSansJP-Black = "assets/fonts/NotoSansJP-Black.otf";
  static const String NotoSansJP-Bold = "assets/fonts/NotoSansJP-Bold.otf";
  static const String NotoSansJP-Light = "assets/fonts/NotoSansJP-Light.otf";
  static const String NotoSansJP-Medium = "assets/fonts/NotoSansJP-Medium.otf";
  static const String NotoSansJP-Regular = "assets/fonts/NotoSansJP-Regular.otf";
  static const String NotoSansJP-Thin = "assets/fonts/NotoSansJP-Thin.otf";
  static const String OFL = "assets/fonts/OFL.txt";
  static const String m = "assets/icons/m.png";
  static const String landscape_1 = "assets/images/profiles/landscape_1.jpg";
  static const String profile2bg = "assets/images/profiles/profile2bg.jpg";
  static const String profile3bg = "assets/images/profiles/profile3bg.jpg";
  static const String profile4bg = "assets/images/profiles/profile4bg.jpg";
  static const String darkbg1 = "assets/images/registration/darkbg1.jpg";
  static const String registration3 = "assets/images/registration/registration3.jpg";
  static const String registration4 = "assets/images/registration/registration4.jpg";
  static const String registrationbg2 = "assets/images/registration/registrationbg2.jpg";
  static const String waves_bg = "assets/images/registration/waves_bg.jpg";
  static const String a = "assets/images/share/a.jpg";
  static const String n = "assets/n.jpg";
}
