/// Generated by AssetsRefGenerator on 2020/10/22
class Res {
  static const String OFL = "assets/fonts/OFL.txt";
  static const String m = "assets/icons/m.png";
  static const String landscape_1 = "assets/images/profiles/landscape_1.jpg";
  static const String profile2bg = "assets/images/profiles/profile2bg.jpg";
  static const String profile3bg = "assets/images/profiles/profile3bg.jpg";
  static const String profile4bg = "assets/images/profiles/profile4bg.jpg";
  static const String darkbg1 = "assets/images/registration/darkbg1.jpg";
  static const String registrationbg2 = "assets/images/registration/registrationbg2.jpg";
  static const String waves_bg = "assets/images/registration/waves_bg.jpg";
  static const String a = "assets/images/share/a.jpg";
  static const String aaaa = "assets/images/share/aaaa.jpg";
  static const String c = "assets/images/share/c.jpg";
  static const String e = "assets/images/share/e.jpg";
  static const String eee = "assets/images/share/eee.jpg";
  static const String err = "assets/images/share/err.jpg";
  static const String ff = "assets/images/share/ff.jpg";
  static const String rr = "assets/images/share/rr.jpg";
  static const String s = "assets/images/share/s.jpg";
  static const String v = "assets/images/share/v.jpg";
  static const String n = "assets/n.jpg";
}
